name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:        
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 28.1
          - snapshot
        ignore_warnings:
          - false
        check:
          - melpa
          - load-file
          - byte-compile
          - checkdoc
          - package-lint
    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@v1.3
      with:
        file: autosync-magit.el
        check: ${{ matrix.check }}
        ignore_warnings: ${{ matrix.ignore_warnings }}
